[project]
name = "rag-against-the-machine"
version = "0.1.0"
description = "Retrieval augmented generation"
requires-python = ">=3.10"
dependencies = [
    "bm25s>=0.3.11",
    "pydantic>=2.13.4",
    "fire>=0.7.1",
    "tqdm>=4.70.0",
    "transformers>=5.16.1",
    "torch>=2.13.0"
]


[dependency-groups]
dev = [
    "flake8",
    "mypy",
]

[tool.mypy]
exclude = ["\\.venv/", "^data/"]
